#!/bin/bash

# Creates the instance according to the response file.
${DB2_DIR}/instance/db2isetup -r ${DB2_CONF}/${DB2_RESP_FILE}

# Starts the created instance.
su -c "db2start" - db2inst1

# Changes to the instance user.
su - db2inst1
